SHELL := /usr/bin/env bash
.SHELLFLAGS := -eu -o pipefail -c

ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

DEFAULT_CONFIG_FILE ?= $(ROOT_DIR)/hack/config.json

IMAGE_REGISTRY ?=
IMAGE_NAME ?= fristonio/kfuzz
IMAGE_TAG ?= cilium
IMAGE_PLATFORM ?= linux/amd64,linux/arm64

##@ Build and Run

build: ## Build the project
	go build -ldflags="-w -s" -o bin/kfuzz .

run: ## Run kfuzz with default configuration(hack/config.json)
	go run ./...

.PHONY: build run

##@ Development

generate: ## Rebuild autogenerated files
	go run ./... log-config > $(DEFAULT_CONFIG_FILE)

test: ## Run the tests
	go test ./...

format: ## Run gofmt for the project
	go fmt ./...

.PHONY: generate test format

##@ Artifacts
docker-build: ## Build docker image.
	docker build -f hack/Dockerfile -t $(IMAGE_NAME):$(IMAGE_TAG)

docker-push: ## Push the Docker image
	docker tag $(IMAGE_NAME):$(IMAGE_TAG) $(IMAGE_REGISTRY)$(IMAGE_NAME):$(IMAGE_TAG)
	docker push $(IMAGE_REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)

docker-buildx-push: ## Build platform specific docker image(requires buildx) and push to registry.
	# https://docs.docker.com/build/building/multi-platform/
	docker buildx build --push \
	    --platform $(IMAGE_PLATFORM) \
		-f hack/Dockerfile \
		-t $(IMAGE_REGISTRY)$(IMAGE_NAME):$(IMAGE_TAG) .

.PHONY: docker-build docker-push docker-buildx-push

##@ Helpers

.PHONY: help
help: ## Display this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
